spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sns
    username: root
    password: 1692
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.sql: debug
